use x-csrf-token from login on UDM platform
Kane610/aiounifi pull request #140
Opened 2022-06-16 06:14 UTC by stonith

The x-csrf-token from the login response should be used instead of the token from the base url response.

fixes https://github.com/home-assistant/core/issues/73071

2022-06-16 06:40 UTC, Kane610 commented
Thanks! I'll have a look tonight

2022-06-16 06:47 UTC, Kane610 commented
You can add a small test that can verify the expected behavior

2022-06-16 19:01 UTC, Kane610 requested changes
I've tested your change and it works fine! Thanks!

Fix failing tests and my comment and I can put out a new release.

2022-06-16 19:01 UTC, Kane610 commented on aiounifi/controller.py
> +                self.headers = {"x-csrf-token": csrf_token}
```suggestion
        if (
            (response := self.last_response) is not None
            and response.status == HTTPStatus.OK
            and (csrf_token := response.headers.get("x-csrf-token")) is not None
        ):
            self.headers = {"x-csrf-token": csrf_token}
```

No need to nest if-statement

2022-06-16 21:12 UTC, stonith commented
I'll try and fix tests tonight.

2022-06-16 21:52 UTC, stonith commented
I don't quite follow what test_unifios_controller_relogin_success test is doing, is this needed?

2022-06-17 05:49 UTC, Kane610 commented
> I don't quite follow what test_unifios_controller_relogin_success test is doing, is this needed?

https://github.com/Kane610/aiounifi/pull/39

2022-06-17 07:28 UTC, Kane610 commented
Looks good! I will look through it tonight and build a new release if everything is as it looks!

2022-06-19 18:15 UTC, Kane610 approved these changes

2022-06-19 18:15 UTC, merged